In [1]:
import tensorflow as tf

In [3]:
X = tf.constant([1,2,3,4])
y = tf.constant([5,6,7,8])


In [5]:
z= tf.multiply(X,y)
z

<tf.Tensor 'Mul:0' shape=(4,) dtype=int32>

In [8]:
sess = tf.Session()
sess.run(z)

array([ 5, 12, 21, 32], dtype=int32)

In [18]:
X1 = tf.placeholder(tf.int32)
y1 = tf.placeholder(tf.int32)

In [19]:
z1= tf.multiply(X1,y1)
z1

<tf.Tensor 'Mul_3:0' shape=<unknown> dtype=int32>

In [21]:
sess = tf.Session()
sess.run(z1, {X1:[[1,2,3,4],[5,6,7,8]], y1:[[4,3,2,1],[5,6,7,8]]})

array([[ 4,  6,  6,  4],
       [25, 36, 49, 64]], dtype=int32)

In [41]:
X2 = tf.placeholder(tf.int32,shape=(2,2))
y2 = tf.placeholder(tf.int32,shape=(2,2))

In [42]:
z2 = tf.multiply(X,y)

In [43]:
sess = tf.Session()
sess.run(z2,{X2:[[1,2],[2,1]],y2:[[1,2],[2,1]]})

array([ 5, 12, 21, 32], dtype=int32)